<?php
$commands = [
	"alpaca" => "Here is a alpaca",
	"announce" => "Announces a message.",
	"ban" => "Bans a user from the guild <strong>(THIS WILL DELETE MESSAGES)</strong><br />Usage: <code>/ban <@user> <time><m/h/d/w/M/Y> [Reason]</code>",
	"birb" => "Here is a birb<br />Aliases: bird",
	"blob" => "Gives you a blob.<br />Usage: <code>/blob [blob name]</code>",
	"botinfo" => "Gets some info about the bot<br />Usage: <code>/botinfo</code><br />Aliases: about, info",
	"cat" => "here is a cat.",
	"chat" => "Have a chat with dunctebot<br />Usage: <code>/chat <message></code>",
	"cleanup" => "performs a cleanup in the channel where the command is run.<br />Aliases: clear",
	"coin" => "flips a coin.<br />Usage: <code>/coin</code>",
	"dialog" => "Gives you a nice dialog",
	"dog" => "here is a dog.",
	"eval" => "A simple eval command<br />Aliases: eval™, evaluate",
	"flip" => "Flips a user.<br />Usage: <code>/flip [@user]</code>",
	"guildinfo" => "Show some stats<br />Aliases: serverinfo, server",
	"hackban" => "Ban a user before he/she can join your guild.<br />Usage: /hackban <userId>",
	"help" => "Shows a list of all the commands.<br />Usage: <code>/help [command]</code><br />Aliases: commands",
	"join" => "Makes the bot join the voice channel that you are in.<br />Aliases: summon, connect",
	"joke" => "See a funny joke. Dad's love them!",
	"kick" => "Kicks a user.",
	"kitty" => "A alternative cat command with more kitties",
	"kpop" => "Gives you a random kpop member, command idea by Exa<br />Usage: /kpop [search term]",
	"leave" => "Makes the bot leave your channel.<br />Aliases: disconnect",
	"list" => "shows the current queue<br />Aliases: queue",
	"llama" => "Here is a llama",
	"nowplaying" => "Prints information about the currently playing song (title, current time)<br />Aliases: np, song",
	"pause" => "Pauses the current song",
	"ping" => "<code>/ping` => Shows the delay from the bot to the discord servers.<br />`/cookie` => blobnomcookie.<br />`/trigger` => use when you are triggered.<br />`/wam` => you need more WAM!.<br />`/mineh` => HERE COMES MINEH!<br />`/invite` => gives you the bot invite<br />`/uptime` => shows the bot uptime<br />`/quote</code> => Shows an inspiring quote<br /><br />Aliases: cookie, trigger, wam, mineh, invite, uptime, quote",
	"play" => "Make the bot play song.<br />Usage: <code>/play [url/search term]</code>",
	"playrw" => "Make the bot play song.<br />Usage: <code>/playrw [url/search term]</code>",
	"pplay" => "Add a playlist to the queue.",
	"repeat" => "Makes the player repeat the currently playing song<br />Aliases: loop",
	"restart" => "Restart the bot or a shard<br />Usage: /restart [shard id]`",
	"seal" => "Here is a nice seal<br />Aliases: zeehond",
	"settings" => "Modify the settings on the bot.<br /><code>/settings` => Shows the current settings<br />`/setPrefix <prefix>` => Sets the new prefix<br />`/setJoinMessage <join message>` => Sets the message that the bot shows when a new member joins<br />`/toggleJoinMessage` => Turns the join message on or off<br />`/toggleSwearFilter` => Turns the swearword filter on or off<br />`/setLogChannel [text channel]</code> => Sets the channel to log messages in<br /><br />Aliases: options, enablejoinmessage, togglejoinmessage, disablejoinmessage, setjoinmessage, enableswearfilter, disableswearfilter, toggleswearfilter, setprefix, setlogchannel",
	"shorten" => "Shortens a url<br />Usage: <code>/shorten <link to shorten></code><br />Aliases: short, url, bitly, googl",
	"shuffle" => "Shuffles the current queue",
	"skip" => "Skips the current track.<br />Aliases: next, nexttrack, skiptrack",
	"softban" => "Kicks a user from the guild <strong>(THIS WILL DELETE MESSAGES)</strong>",
	"stop" => "Stops the music player.",
	"tag" => "Save it in a tag<br />Usage: <code>/tag <tag_name/author/delete/create/help> [tag_name] [tag contents]</code><br />Aliases: pasta, tags, t",
	"ttb" => "Convert your text to bricks",
	"unban" => "Unbans a user",
	"update" => "Update the bot and restart",
	"userinfo" => "Get information from yourself or from another user.<br />Usage: <code>/userinfo [username]</code><br />Aliases: user, i",

];