# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build

on:
    push:
    pull_request:

jobs:
    build:
        env:
            CI: true

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - name: Set up java
              uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 19
            - name: Grant execute permission for gradlew
              run: chmod +x gradlew
            - name: build all needed
              run: ./gradlew --no-daemon buildNeeded --warning-mode=summary

    build_docker:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
              with:
                  path: './'
                  fetch-depth: 0

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build bot
              id: docker_build_bot
              uses: docker/build-push-action@v3
              with:
                  file: ./bot/Dockerfile
                  context: ./
                  push: false
                  tags: dunctebot/skybot:latest
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new
                  build-args: |
                      is_ci=true
                      git_sha=${{ github.sha }}

            - name: Build dash
              id: docker_build_dash
              uses: docker/build-push-action@v3
              with:
                  file: ./dashboard/Dockerfile
                  context: ./
                  push: false
                  tags: dunctebot/dashboard:latest
                  cache-from: type=local,src=/tmp/.buildx-cache
                  cache-to: type=local,dest=/tmp/.buildx-cache-new
                  build-args: |
                      is_ci=true
                      git_sha=${{ github.sha }}

            # Temp fix
            # https://github.com/docker/build-push-action/issues/252
            # https://github.com/moby/buildkit/issues/1896
            - name: Move cache
              run: |
                  rm -rf /tmp/.buildx-cache
                  mv /tmp/.buildx-cache-new /tmp/.buildx-cache


